# Generated by Django 4.0 on 2022-01-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
